### ISSUE TITLE
1.1 dependency causes error running uberwar

### ISSUE THREAD

**Issue by rplevy** [alienscience/leiningen-war#1]
When I tried to create an uberwar in Ubuntu using the latest Leiningen and Clojure & contrib 1.2.0 snapshots, I got the error 'Exception in thread "main" java.lang.NoSuchMethodError: clojure.lang.RestFn.<init>(I)V'.  This seems to have to do with the library being compiled with dependencies on Clojure 1.1.  It seems like the project just needs be updated to depend on clojure & contrib 1.2.0 snapshots, because I found that doing a local lein install of leiningen-war with the project file modified to depend on clojure & contrib 1.2, and then linking to that jar in my project's lib, allowed me to run the uberwar task without getting this error.

**Comment by alienscience** [comment]
This should be fixed now in release 0.0.7. The plugin is no longer AOT compiled and should work across clojure versions.
