### ISSUE TITLE
leiningen 2 compatibility

### ISSUE THREAD

**Issue by rplevy-draker** [alienscience/leiningen-war#10]
Does anyone have a fork with this already working?

**Comment by alienscience** [comment]
Hello,
  I don't know of any active  forks of this project. I would gladly add L2 compatibility but I am forbidden from contributing to opensource projects by my employer (I've handed in my notice though so in 5 months I'll be a free man again).

If the normal Ring plugins (I can't remember their names sorry) aren't satisfactory for building WAR files then please feel free to fork project and I'll link to the fork. Another, possibly easier option, is to contact the Ring plugin authors if their plugins are missing features you want. About a year ago the existing plugins didn't handle mixed java/clojure web applications but things may have changed.

A third option is to make your own plugin. Leiningen WAR is functional but not particularly elegant - I'm sure you can rip out whatever code you want and make something better.

Good luck with whatever you choose and I apologise for not being able to help.

**Comment by rplevy-draker** [comment]
Actually, I learned on IRC shortly after posting this that "lein ring war/uberwar" exists.  I actually didn't know that because your leiningen-war continued to work just fine up until the preview release of lein 2 so I always used that.  So I guess lein ring war deprecates leiningen-war going forward.  Thanks! --Rob

PS: congrats on your liberation from that anti-FOSS employer! :)

**Comment by kumarshantanu** [comment]
I think `leiningen-war` has its own place despite the existence of `lein-ring`, especially when working on Java projects or projects in other JVM languages where you need to build a WAR from a given servlet class. Leiningen 2 compatibility would be certainly welcome!

**Comment by rplevy-draker** [comment]
+1, I didn't consider that.  Leiningen is useful beyond just Clojure!

**Comment by kumarshantanu** [comment]
I forgot to post this here earlier--I have created [lein-servlet](https://github.com/kumarshantanu/lein-servlet) to work with servlet based webapps, which supports the `war` task beside other tasks.

**Comment by alienscience** [comment]
Cool, I'll put a link to lein-servlet.
