### ISSUE TITLE
web.xml is copied to WEB-INF/classes in war

### ISSUE THREAD

**Issue by standyck** [alienscience/leiningen-war#4]
When using lein uberwar and the web.xml in the default path of $PROJECT/src/web.xml a call to lein uberwar constructs a war file with a web.xml in the WEB-INF directory and also in the WEB-INF/classes directory. The web.xml in the WEB-INF/classes directory is extraneous.

**Comment by alienscience** [comment]
That was lazy programming on my part -- I'll hopefully fix this today and then do a release.

**Comment by alienscience** [comment]
This should be fixed in Release 0.0.11
