### ISSUE TITLE
Can uberwar ignore dot directories?

### ISSUE THREAD

**Issue by standyck** [alienscience/leiningen-war#5]
Not so much an issue as a feature request. My servlet code is stored under subversion. The uberwar task copies all the .svn directories and their contents into the war. It might be nice if it would automatically exclude dot directories when creating a war file.

**Comment by alienscience** [comment]
I'll try and do this today. Many thanks for the feedback.

**Comment by alienscience** [comment]
This should be fixed in release 0.0.11

**Comment by standyck** [comment]
Thanks. You rock!
