### ISSUE TITLE
lib folder not being put in war on server (but works fine on laptop)

### ISSUE THREAD

**Issue by sethtrain** [alienscience/leiningen-war#6]
I don't know how much of an issue this is and even if it is a problem for anyone else but I am experiencing a problem with using leiningen-war on our deployment server.  I am running the same version of lein on both my computer and my server.  Everything works fine on my computer but when using leiningen-war on my server (Ubuntu LTS 10.04) the lib directory isn't being copied into the war when running lein uberwar.  Again this works on my Mac just not my server.

**Comment by alienscience** [comment]
Sorry for the slow reply - I was not by a computer over Christmas :-) 

I haven't ever seen this behaviour but will try lein war on a 10.04 virtual host that I have access to.

**Comment by sethtrain** [comment]
Okay, so I have figured out what is going on here.  I am using Hudson to build my application and the default folder structure for hudson is ".hudson/...".  Well, this causes the `hidden?` function to fail on every file.

**Comment by alienscience** [comment]
Apologies for not closing this - it was fixed in the last release.
